//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model_medical
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class medicalEntities : DbContext
    {
        public medicalEntities()
            : base("name=medicalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rdv_status> rdv_status { get; set; }
        public virtual DbSet<type_rdv> type_rdv { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<patient> patient { get; set; }
        public virtual DbSet<rdv> rdv { get; set; }
    
        public virtual ObjectResult<getAllRdv_Result> getAllRdv()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllRdv_Result>("getAllRdv");
        }
    }
}
