//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model_medical
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public decimal id { get; set; }
        public Nullable<int> fiche_number { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string adress { get; set; }
        public string tel { get; set; }
        public string profession { get; set; }
        public int isSync { get; set; }
    }
}
