//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace model_medical
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdv
    {
        public decimal id { get; set; }
        public decimal patient_id { get; set; }
        public System.DateTime date_rdv { get; set; }
        public int isSync { get; set; }
        public int type_id { get; set; }
        public int status_id { get; set; }
    }
}
